# Generated by Django 2.2.1 on 2019-06-20 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190619_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='answer_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='answer_massage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
